version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    env_file:
      - ./env/api.env
    depends_on: 
      - mydb
      - myredis
  smartbrain-app:
    build: 
      context: ./front
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
  mydb:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - ./env/postgresql.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/tables:/docker-entrypoint-initdb.d
    # network_mode: "host"
  myredis:
    image: redis
volumes:
  api_node_modules:
  pgdata: 
    