version: "3.8"
services:
  heroku-front:
    build: 
      context: ./
      dockerfile: heroku.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public