version: "3.8"
services:
  myheroku:
    build: 
      context: ./
      dockerfile: heroku.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - api_node_modules:/app/node_modules
volumes:
  api_node_modules:
    